//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popcorn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Popcorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        public static string ActorsLabel {
            get {
                return ResourceManager.GetString("ActorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering.
        /// </summary>
        public static string BufferingLabel {
            get {
                return ResourceManager.GetString("BufferingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to have an internet connection error. Please retry..
        /// </summary>
        public static string ConnectionErrorDescriptionPopup {
            get {
                return ResourceManager.GetString("ConnectionErrorDescriptionPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error.
        /// </summary>
        public static string ConnectionErrorTitlePopup {
            get {
                return ResourceManager.GetString("ConnectionErrorTitlePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently playing.
        /// </summary>
        public static string CurrentlyPlayingLabel {
            get {
                return ResourceManager.GetString("CurrentlyPlayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors.
        /// </summary>
        public static string DirectorsLabel {
            get {
                return ResourceManager.GetString("DirectorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download limit (kB/s).
        /// </summary>
        public static string DownloadLimitLabel {
            get {
                return ResourceManager.GetString("DownloadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movie found.
        /// </summary>
        public static string EmptySearchLabel {
            get {
                return ResourceManager.GetString("EmptySearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greatest.
        /// </summary>
        public static string GreatestTitleTab {
            get {
                return ResourceManager.GetString("GreatestTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading trailer....
        /// </summary>
        public static string LoadingTrailerLabel {
            get {
                return ResourceManager.GetString("LoadingTrailerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie quality.
        /// </summary>
        public static string MovieQualityLabel {
            get {
                return ResourceManager.GetString("MovieQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MovieSettingsLabel {
            get {
                return ResourceManager.GetString("MovieSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string PlayingTitleTab {
            get {
                return ResourceManager.GetString("PlayingTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayLabel {
            get {
                return ResourceManager.GetString("PlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string PopularTitleTab {
            get {
                return ResourceManager.GetString("PopularTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentTitleTab {
            get {
                return ResourceManager.GetString("RecentTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ReloadLabel {
            get {
                return ResourceManager.GetString("ReloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchBoxWatermark {
            get {
                return ResourceManager.GetString("SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTitleTab {
            get {
                return ResourceManager.GetString("SearchTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuTitle {
            get {
                return ResourceManager.GetString("SettingsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        public static string SubtitlesLabel {
            get {
                return ResourceManager.GetString("SubtitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        public static string TrailerButton {
            get {
                return ResourceManager.GetString("TrailerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload limit (kB/s).
        /// </summary>
        public static string UploadLimitLabel {
            get {
                return ResourceManager.GetString("UploadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string WatchButton {
            get {
                return ResourceManager.GetString("WatchButton", resourceCulture);
            }
        }
    }
}
