---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Popcorn - Watch movies easier"
keywords:    "Popcorn, .NET, movies, streaming, watch"
description: "Popcorn is a project which aims to provide a simple interface to watch any movie."
source_link: "https://github.com/bbougot/Popcorn"
favicon:     "https://raw.githubusercontent.com/bbougot/Popcorn/master/Popcorn/icon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-66418508-1"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  
